### ISSUE TITLE
Question: Indexer for ke_search

### ISSUE THREAD

**Issue by kimchristiansen** [b13/listelements#18]
I am using listelements in a TYPO3 Project in combination with ke_sarch.
Is there already a ke_search indexer for the listelements records or has anyone done something like this before?

**Comment by chriskrj** [comment]
Any News on this? or Best Practices?

**Comment by kimchristiansen** [comment]
I made a hook. for ke_search modifyPageContentFields and modifyContentFromContentElement. I have sent you the hook via DM.
