### ISSUE TITLE
Question: What are the usecases in your company for that extension?

### ISSUE THREAD

**Issue by josefglatz** [b13/listelements#28]

**Comment by bmack** [comment]
I use it in my projects for basically everything. tbh, I use listelements more often than EXT:container (as a user).

It basically is a default inline table for custom CEs with multiple items.

A few examples for custom CEs I use listelements:
* A Banner with multiple CTAs (where 1 CTA is a list element with "link", "linktext" and "linkconfig") where you have multiple (e.g. max 3) CTA buttons
* "Feature List CE" A list of features for a specific product with images and a bodytext
* "Timeline CE" A list of timeline items which can be added dynamically
* "Tiles" CE: A list of tiles (e.g. for showing a list of services offered by a customer)

I do not need to write
* DataProcessor
* Create a custom IRRE table
* Only create some TCA functionality for my actual main CE

**Comment by achimfritz** [comment]
thanks to @bmack , i closed this issue
