### ISSUE TITLE
Listelement Items empty

### ISSUE THREAD

**Issue by kimchristiansen** [b13/listelements#8]
I wanted to test this promising extension. I installed and configured the extension via composer as described in the instructions and created a content element.

Now I can create listelements, but not edit them. Not even the title field is editable. 

Did I miss something?

Setup:
TYPO3 10.4.17
PHP 7.3.x
list elements 0.2.1

Further extensions:
container
content_defender

![listelements-empty](https://user-images.githubusercontent.com/1137499/129928070-0a510b80-68ce-44ad-b048-b48019cbf607.png)

Thanks in advance!

**Comment by davidsteeb** [comment]
Yes, we are still in the process of finishing up work here, and the documentation is lacking.

Here's what I suppose is missing: You need to add a `showitem` configuration to your element for the list items. This might look like this:

```
$GLOBALS['TCA']['tt_content']['types']['<yourelement>']['columnsOverrides'] = [
    // configuration for this element's tt_content field configuration
    'header' => [
        'description' => 'Description for the header field of the tt_content element',
    ],
    'tx_listelements_list' => [
        'label' => 'My List Item Label',
        'config' => [
            'appearance' => [
                'newRecordLinkTitle' => 'Add a new item to my list',
            ],
            'overrideChildTca' => [
                // add a showitem configuration for the list items for this CType
                'types' => [
                    '0' => [
                        'showitem' => '
                                header,
                                text,
                                --palette--;;hiddenpalette', // always include the hidden palette (languages)
                    ],
                ],
                'columns' => [
                    // change configuration for fields for list items here (for this CType's list items)
                    'text' => [
                        'config' => [
                            'rows' => 5,
                        ],
                    ],
                ],
            ],
        ],
    ],
];
```

You can change the fields for list items for each CType you create.

**Comment by kimchristiansen** [comment]
Thank you very much for the quick answer. That was the missing piece of information. Keep up the good work!
